### ISSUE TITLE
Issue with firebase-messaging version

### ISSUE THREAD

**Issue by schusss** [Iterable/iterable-android-sdk#222]
Hi, I'm integrating the latest firebase-crashlytics lib and for this, I need google services 4.3.3.
It also needs the latest firebase-iid version.
Iterable sdk is failling my compilation as it's using 17.4.0 instead of the latest one.
I tried transitive and exclude, but couldn't make it work. Any idea ?

```
  Dependency failing: com.google.firebase:firebase-messaging:17.4.0 -> com.google.firebase:firebase-iid@[17.1.0], but fire
  base-iid version was 19.0.0.
```

these are the versions I'm using:
```
iterable                          : "com.iterable:iterableapi:3.2.2",
firebase_analytics         : "com.google.firebase:firebase-analytics:17.3.0",
firebase_crashlytics      : "com.google.firebase:firebase-crashlytics:17.0.0-beta04",
firebase_messaging      : "com.google.firebase:firebase-messaging:20.1.5",
```

Thank you for your help,

**Comment by vbabenkoru** [comment]
Thank you for the report. We'll investigate and get back to you.

**Comment by vbabenkoru** [comment]
I couldn't reproduce the issue. Importing these dependencies worked fine. Try running `./gradlew dependencies` to check how `com.google.firebase:firebase-messaging` is resolved. If you specify `com.google.firebase:firebase-analytics:17.3.0` in your `build.gradle`, it should never 'downgrade' it due to another transitive dependency. In our tests, gradle always uses a higher version if it is specified or required by other dependencies.

**Comment by vbabenkoru** [comment]
Here is how `iterableapi` dependency branch looks like:
```
|    \--- com.iterable:iterableapi:3.2.2
...
|         \--- com.google.firebase:firebase-messaging:17.4.0 -> 20.1.5
...
|              +--- com.google.firebase:firebase-iid:[20.1.5] -> 20.1.5
```
This means that the transitive dependencies have been upgraded to the highest version required by anything else in the dependency tree.

**Comment by schusss** [comment]
because i removed firebase-core, it did miss the firebase-iid again, in one of my module.
Thanks for your help, it works now!
