### ISSUE TITLE
Android: new firebase cloud messaging api (v1)

### ISSUE THREAD

**Issue by MathieuChabas** [Iterable/iterable-android-sdk#677]
Hello,

Firebase deprecated their legacy cloud messaging api, which will be discontinued on June 20, 2024. Their new api relies on OAuth2 access tokens (which can be created using a service account's private key) instead of a server key. 

Will you support this new api? If so, do you have a deadline when it will be available?

Thanks!

**Comment by davidtruong** [comment]
@MathieuChabas Yes, we will definitely going to be supporting the new Firebase HTTP V1.
We are currently working with Amazon on some infrastructure changes to support this new version of the api and hope to get a beta version up as soon as we can. I can't provide a definitive timeline at the moment, but be on the lookout for that.

**Comment by davidtruong** [comment]
@MathieuChabas Update:
We are working on support changes for the support to move to the new auth structure.

Good news is that there are no code changes to the underlying APIs. The only required changes would be uploading a new google services json file instead of the legacy key.

Will provide a further update when we have that option available in the Iterable Portal.

**Comment by MathieuChabas** [comment]
@davidtruong Awesome, that's great news!

**Comment by grndvl1** [comment]
Any word on this as it 4 months off and we need time to migrate some systems
